name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-and-test:
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v5

            -   name: Build
                run: make build

            -   name: Test
                run: |
                    make run
                    make test
